const BASE_ENDPOINT = process.env.NEXT_PUBLIC_BASE_URL;

const POSTS_ENDPOINT = `${BASE_ENDPOINT}/boards`;

const MENUS_ENDPOINT = `${BASE_ENDPOINT}/boardMenus`;

const NOTIFICATIONS_ENDPOINT = `${BASE_ENDPOINT}/notifications`;

export { BASE_ENDPOINT, POSTS_ENDPOINT, MENUS_ENDPOINT, NOTIFICATIONS_ENDPOINT };
